name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Cache cargo dependencies
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache cargo index
        uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-git-

      - name: Cache cargo build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Rust project
        run: cargo build --release

      # Login to ACR
      - name: Azure Container Registry Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      # Build Docker with build cache
      - name: Build Docker image
        run: |
          docker build \
            --cache-from ecrvubnera.azurecr.io/vulnera-app:latest \
            --file scripts/docker/Dockerfile \
            -t ecrvubnera.azurecr.io/vulnera-app:latest \
            -t ecrvubnera.azurecr.io/vulnera-app:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ecrvubnera.azurecr.io/vulnera-app:latest
          docker push ecrvubnera.azurecr.io/vulnera-app:${{ github.sha }}
